version: '3.0'  

services:
  notary: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: notary 
    ports:
      - "10002:10200"
      - "10003:10201"
    volumes:
      - ./Network/Notary/node.conf:/etc/corda/node.conf
      - ./Network/Notary/certificates:/opt/corda/certificates
      - ./Network/Notary/persistence:/opt/corda/persistence
      - ./Network/Notary/logs:/opt/corda/logs
      - ./Network/Shared/corda.jar:/opt/corda/bin/corda.jar  #Enterprise
      - ./Network/Shared/cordapps:/opt/corda/cordapps
      - ./Network/Shared/node-infos:/opt/corda/additional-node-infos
      - ./Network/Shared/network-parameters:/opt/corda/network-parameters:ro


  partya: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: partya
    ports:
      - "10005:10200"
      - "10006:10201"
      - "2222:2222"
    command: java -Dcapsule.jvm.args="-javaagent:/opt/corda/drivers/prometheus-jmx-exporter.jar=8080:/opt/corda/config.yml" -jar /opt/corda/bin/corda.jar --base-directory /opt/corda --config-file /etc/corda/node.conf
    volumes:
      - ./Network/PartyA/node.conf:/etc/corda/node.conf
      - ./Network/PartyA/certificates:/opt/corda/certificates
      - ./Network/PartyA/persistence:/opt/corda/persistence
      - ./Network/PartyA/logs:/opt/corda/logs
      - ./Network/Shared/corda.jar:/opt/corda/bin/corda.jar  #Enterprise
      - ./Network/Shared/cordapps:/opt/corda/cordapps
      - ./Network/Shared/node-infos:/opt/corda/additional-node-infos
      - ./Network/Shared/network-parameters:/opt/corda/network-parameters
      - ./prometheus/prometheus-jmx-exporter.jar:/opt/corda/drivers/prometheus-jmx-exporter.jar
      - ./prometheus/config.yml:/opt/corda/config.yml


  partyb: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: partyb 
    ports:
      - "10008:10200"
      - "10009:10201"
    volumes:
      - ./Network/PartyB/node.conf:/etc/corda/node.conf
      - ./Network/PartyB/certificates:/opt/corda/certificates
      - ./Network/PartyB/persistence:/opt/corda/persistence
      - ./Network/PartyB/logs:/opt/corda/logs
      - ./Network/Shared/corda.jar:/opt/corda/bin/corda.jar  #Enterprise
      - ./Network/Shared/cordapps:/opt/corda/cordapps
      - ./Network/Shared/node-infos:/opt/corda/additional-node-infos
      - ./Network/Shared/network-parameters:/opt/corda/network-parameters


  partyc: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: partyc 
    ports:
      - "10011:10200"
      - "10012:10201"
    volumes:
      - ./Network/PartyC/node.conf:/etc/corda/node.conf
      - ./Network/PartyC/certificates:/opt/corda/certificates
      - ./Network/PartyC/persistence:/opt/corda/persistence
      - ./Network/PartyC/logs:/opt/corda/logs
      - ./Network/Shared/corda.jar:/opt/corda/bin/corda.jar  #Enterprise
      - ./Network/Shared/cordapps:/opt/corda/cordapps
      - ./Network/Shared/node-infos:/opt/corda/additional-node-infos
      - ./Network/Shared/network-parameters:/opt/corda/network-parameters


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "8000:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8010:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    links:
      - prometheus